"""Opt-in, advisory LLM research-review layer for ClaimCI.

The deterministic auditor remains in :mod:`claimci.audit`.  This package keeps
review-only models and provider output separate from ClaimCI's authoritative
finding and verdict types.
"""

from .models import (
    ChangeEntry,
    ChangeInventory,
    ChangeInventorySource,
    ChangeStatus,
    ClaimDirection,
    ClaimMagnitude,
    ClaimType,
    ComparisonBasis,
    ExactMaterialOmission,
    GateDisposition,
    MaterialClaimSeed,
    MagnitudeKind,
    PreflightGateResult,
    ProviderCallRecord,
    ProviderLifecycle,
    ProviderUsage,
    ReviewConfig,
    ReviewError,
    ReviewLimits,
    ReviewMaterialKind,
    ReviewPreflight,
    ReviewScope,
    ReviewStatus,
    ScientificClaim,
    SourceBundle,
    SourceKind,
    SourceLocation,
    SourceRecord,
    SnapshotIdentity,
    SnapshotRole,
    ScopeIssue,
)
from .analysis_bridge import (
    AnalysisReviewContext,
    run_analysis_review,
    validate_scientific_claim_for_audit,
)
from .inventory import build_git_change_inventory
from .preflight import preflight_review

__all__ = [
    "AnalysisReviewContext",
    "ChangeEntry",
    "ChangeInventory",
    "ChangeInventorySource",
    "ChangeStatus",
    "ClaimDirection",
    "ClaimMagnitude",
    "ClaimType",
    "ComparisonBasis",
    "ExactMaterialOmission",
    "GateDisposition",
    "MaterialClaimSeed",
    "MagnitudeKind",
    "ProviderCallRecord",
    "ProviderLifecycle",
    "PreflightGateResult",
    "ProviderUsage",
    "ReviewConfig",
    "ReviewError",
    "ReviewLimits",
    "ReviewMaterialKind",
    "ReviewPreflight",
    "ReviewScope",
    "ReviewStatus",
    "ScientificClaim",
    "SourceBundle",
    "SourceKind",
    "SourceLocation",
    "SourceRecord",
    "SnapshotIdentity",
    "SnapshotRole",
    "ScopeIssue",
    "build_git_change_inventory",
    "preflight_review",
    "run_analysis_review",
    "validate_scientific_claim_for_audit",
]
