"""Shared immutable contracts for ClaimCI zero-configuration analysis."""

from __future__ import annotations

from typing import TYPE_CHECKING

from claimci.measurement import (
    MeasurementComponentKind,
    UpstreamAggregationProcedure,
)

from .confidence import Confidence
from .claims import (
    audit_claim_spec_from_research_spec,
    audit_relevant_claim_projection,
)
from .claim_types import (
    AbsoluteMetricClaim,
    CanonicalScientificClaim,
    ClaimBoundComparator,
    ClaimConstraint,
    ClaimEvidencePolicy,
    ClaimQuantity,
    ClaimTypeContractError,
    EvaluationConstraint,
    EvaluationConstraintKind,
    GeneralizationClaim,
    GenericQuantitativeClaim,
    MetricImprovementClaim,
    PrimaryClaimKind,
    PrimaryScientificClaim,
    UNSUPPORTED_DETERMINISTIC_CLAIM_COMPILER,
    UnsupportedDeterministicClaimCompiler,
    claim_evidence_policy,
    claim_semantic_projection,
    compile_audit_claim,
    recover_scientific_claim,
)
from .contracts import (
    Adapter,
    AdapterMatch,
    AdvisoryResearchInterpretation,
    AnalysisAuthority,
    AnalysisContractError,
    AnalysisState,
    ArtifactCandidate,
    ArtifactBinding,
    ArtifactKind,
    AuditClaimSpec,
    ClaimReference,
    ClaimedMetricValue,
    ComputeEvidence,
    ConfigValue,
    DatasetSplit,
    DatasetReference,
    DeterministicAuditOutcome,
    EphemeralAuditPlan,
    EvidenceSelector,
    ExperimentRole,
    FieldMapping,
    FieldProvenance,
    GitCommitSha,
    MappingCandidate,
    MappingChoice,
    MappingQuestion,
    MappingTrust,
    MissingEvidence,
    NormalizedEvidence,
    NormalizedObservation,
    PassiveArtifact,
    ProvenanceKind,
    RepoMapping,
    RepositoryIdentity,
    RepositoryPath,
    SelectorKind,
    Sha256Digest,
    TablePredicate,
    TableScalarType,
    TableSelector,
    UnifiedAnalysisResult,
    field_mapping_identity,
    selector_identity,
    to_jsonable,
)
from .obligations import (
    ArtifactEvidenceSlot,
    ArtifactEvidenceSupport,
    ClaimFieldKind,
    ClaimFieldSupport,
    ClaimFieldTarget,
    EvidenceObligationDecision,
    EvidenceObligationEffect,
    EvidenceObligation,
    EvidenceObligationBundle,
    EvidenceObligationReason,
    EvidenceObligationState,
    MeasurementComponentTarget,
    MeasurementProcedureSupport,
    ObligationSupportReference,
    ObligationTarget,
    assess_evidence_obligations,
    claim_field_support,
    evidence_obligations_json_bytes,
    legacy_missing_evidence,
    validated_artifact_support,
    validated_measurement_procedure_support,
)
from .measurement import (
    UpstreamProcedureRequirement,
    recover_upstream_procedure_requirement,
)
from .planner import (
    PlanningOutcome,
    PlanningRequest,
    PlanningState,
    derive_ephemeral_plan_id,
    plan_ephemeral_audit,
    planning_request_from_discovery,
)
from .materialize import (
    MaterializationError,
    MaterializationLimits,
    MaterializationPartial,
    MaterializationUnavailable,
    RuntimeExecutionContext,
    execute_ephemeral_audit,
    execute_ephemeral_audit_with_trace,
)
from .trace import (
    AdvisoryResearchTrace,
    BoundedValueRepresentation,
    DeterministicAuditTrace,
    EVIDENCE_TRACE_MAX_BYTES,
    EVIDENCE_TRACE_VERSION,
    EphemeralAuditExecution,
    EvidenceTraceBundle,
    EvidenceTraceEntry,
    TraceAuthorityClass,
    TraceCompleteness,
    TraceContractError,
    TraceLimitError,
    TraceRecordKind,
    TraceSelector,
    TraceTablePredicate,
    TraceValueType,
    trace_json_bytes,
)

if TYPE_CHECKING:
    from claimci.review.models import ReviewConfig
    from claimci.review.provider import ReviewerProvider


def run_unified_analysis(
    request: PlanningRequest,
    runtime: RuntimeExecutionContext,
    review_config: "ReviewConfig",
    *,
    provider: "ReviewerProvider | None" = None,
) -> UnifiedAnalysisResult:
    """Load the hosted orchestration lazily to keep Review imports acyclic."""

    from .integration import run_unified_analysis as implementation

    return implementation(
        request,
        runtime,
        review_config,
        provider=provider,
    )

__all__ = [
    "Adapter",
    "AdapterMatch",
    "AdvisoryResearchTrace",
    "AdvisoryResearchInterpretation",
    "AnalysisAuthority",
    "AnalysisContractError",
    "AnalysisState",
    "ArtifactCandidate",
    "ArtifactBinding",
    "ArtifactEvidenceSlot",
    "ArtifactEvidenceSupport",
    "ArtifactKind",
    "AuditClaimSpec",
    "AbsoluteMetricClaim",
    "BoundedValueRepresentation",
    "CanonicalScientificClaim",
    "ClaimBoundComparator",
    "ClaimConstraint",
    "ClaimEvidencePolicy",
    "ClaimFieldKind",
    "ClaimFieldSupport",
    "ClaimFieldTarget",
    "ClaimQuantity",
    "ClaimReference",
    "ClaimTypeContractError",
    "ClaimedMetricValue",
    "ComputeEvidence",
    "Confidence",
    "ConfigValue",
    "DatasetSplit",
    "DatasetReference",
    "DeterministicAuditOutcome",
    "DeterministicAuditTrace",
    "EVIDENCE_TRACE_MAX_BYTES",
    "EVIDENCE_TRACE_VERSION",
    "EphemeralAuditExecution",
    "EphemeralAuditPlan",
    "EvidenceSelector",
    "EvidenceObligationDecision",
    "EvidenceObligationEffect",
    "EvidenceObligation",
    "EvidenceObligationBundle",
    "EvidenceObligationReason",
    "EvidenceObligationState",
    "EvidenceTraceBundle",
    "EvidenceTraceEntry",
    "EvaluationConstraint",
    "EvaluationConstraintKind",
    "ExperimentRole",
    "FieldMapping",
    "FieldProvenance",
    "GitCommitSha",
    "GeneralizationClaim",
    "GenericQuantitativeClaim",
    "MappingCandidate",
    "MappingChoice",
    "MappingQuestion",
    "MappingTrust",
    "MaterializationError",
    "MaterializationLimits",
    "MaterializationPartial",
    "MaterializationUnavailable",
    "MeasurementComponentKind",
    "MeasurementComponentTarget",
    "MeasurementProcedureSupport",
    "MetricImprovementClaim",
    "MissingEvidence",
    "NormalizedEvidence",
    "NormalizedObservation",
    "ObligationSupportReference",
    "ObligationTarget",
    "assess_evidence_obligations",
    "PassiveArtifact",
    "PlanningOutcome",
    "PlanningRequest",
    "PlanningState",
    "PrimaryClaimKind",
    "PrimaryScientificClaim",
    "ProvenanceKind",
    "RepoMapping",
    "RepositoryIdentity",
    "RepositoryPath",
    "RuntimeExecutionContext",
    "SelectorKind",
    "Sha256Digest",
    "TablePredicate",
    "TableScalarType",
    "TableSelector",
    "TraceAuthorityClass",
    "TraceCompleteness",
    "TraceContractError",
    "TraceLimitError",
    "TraceRecordKind",
    "TraceSelector",
    "TraceTablePredicate",
    "TraceValueType",
    "UNSUPPORTED_DETERMINISTIC_CLAIM_COMPILER",
    "UnifiedAnalysisResult",
    "UpstreamAggregationProcedure",
    "UpstreamProcedureRequirement",
    "UnsupportedDeterministicClaimCompiler",
    "to_jsonable",
    "audit_claim_spec_from_research_spec",
    "audit_relevant_claim_projection",
    "claim_evidence_policy",
    "claim_field_support",
    "evidence_obligations_json_bytes",
    "legacy_missing_evidence",
    "claim_semantic_projection",
    "compile_audit_claim",
    "derive_ephemeral_plan_id",
    "execute_ephemeral_audit",
    "execute_ephemeral_audit_with_trace",
    "plan_ephemeral_audit",
    "planning_request_from_discovery",
    "recover_scientific_claim",
    "recover_upstream_procedure_requirement",
    "run_unified_analysis",
    "field_mapping_identity",
    "selector_identity",
    "trace_json_bytes",
    "validated_artifact_support",
    "validated_measurement_procedure_support",
]
